name: Test and Create Release

on:
  push:
    branches: ['main']

env:  
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd src
          pip install -r requirements.txt
          cd test
          python test.py

  create-release:
    needs: execute-tests
    if: success()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
